services:

  api: 
    image: ghcr.io/gchalard/vulnerable-app-api:latest
    environment:
      DB_URI: postgresql://user:password@postgres:5432/db
    ports:
      - 1234:5000
  keycloak:
    image: ghcr.io/gchalard/vulnerable-app-kc:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false

    command: start
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/gchalard/vulnerable-app-front:latest
    ports:
      - 2345:3000

  postgres:
    image: ghcr.io/gchalard/vulnerable-app-db:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5