services:

  api: 
    image: ghcr.io/gchalard/vulnerable-app-api:latest
    environment:
      DB_URI: postgresql://user:password@postgres:5432/db
    ports:
      - 1234:5000
    depends_on:
      postgres:
        condition: service_healthy
  keycloak:
    image: ghcr.io/gchalard/vulnerable-app-kc:latest
    command: start
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/gchalard/vulnerable-app-front:latest
    ports:
      - 2345:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: ghcr.io/gchalard/vulnerable-app-db:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5