name: BUILD AND PUBLISH LATEST IMAGES
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup docker
              uses: docker/setup-buildx-action@v2
            - name: Login to GitHub Container Registry
              run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u gchalard --password-stdin
            - name: Build and push
              uses: docker/bake-action@v6
              with:
                push: true
                files: bake.hcl
                github-token: ${{ secrets.PAT }}
            